source-config = {
  bootstrap-servers = "localhost:9092"
  bootstrap-servers = ${?SOURCE_BOOTSTRAP_SERVERS}

  schema-registry-url = "http://localhost:8081"
  schema-registry-url = ${?SOURCE_SCHEMA_REGISTRY_URL}

  topic = "my-clicks"
  topic = ${?SOURCE_TOPIC}

  kafka-group-id = "kafka-elastic-forwarder-group"
  kafka-group-id = ${?SOURCE_KAFKA_GROUP_ID}
}

sink-config = {
  host = "localhost"
  host = ${?SINK_HOST}

  port = 9200
  port = ${?SINK_PORT}

  index-name = "my-clicks"
  index-name = ${?SINK_INDEX_NAME}
}

forwarder-config = {
  batch-size = 10
  batch-size = ${?FORWARDER_BATCH_SIZE}

  batch-timeout = 10s
  batch-timeout = ${?FORWARDER_BATCH_TIMEOUT}
}
